---
- name: Check if Java is already installed
  shell: java -version                         # ✅ uses shell for PATH resolution
  register: java_check
  ignore_errors: yes

- name: Print existing Java version (if installed)
  debug:
    msg: "{{ java_check.stderr_lines | default(['Java not installed']) }}"
  when: java_check.rc == 0

- name: Install Java if not present
  become: true                                 # ✅ ADDED to run yum as root
  yum:
    name: "{{ java_package }}"
    state: present
  when: java_check.rc != 0











# # - include: ping.yml
# # - include: traceroute.yml

# - name: Ping the host
#   ansible.builtin.ping:

# - name: Display whoami
#   ansible.builtin.command: whoami
#   register: whoami_output

# - name: Show logged-in user
#   ansible.builtin.debug:
#     msg: "Logged in as: {{ whoami_output.stdout }}"

