---
- name: Update yum cache
  yum:
    update_cache: yes
    use_backend: dnf

- name: Install latest OpenJDK 17
  yum:
    name: java-17-openjdk
    state: present
    use_backend: dnf

- name: Install OpenJDK 17 Development Tools (optional)
  yum:
    name: java-17-openjdk-devel
    state: present
    use_backend: dnf

# # - include: ping.yml
# # - include: traceroute.yml

# - name: Ping the host
#   ansible.builtin.ping:

# - name: Display whoami
#   ansible.builtin.command: whoami
#   register: whoami_output

# - name: Show logged-in user
#   ansible.builtin.debug:
#     msg: "Logged in as: {{ whoami_output.stdout }}"

