- name: Ping 
  shell: ping -c 1 -q -W 1 {{ item }}
  loop: "{{ groups['destinations'] }}"
  register: command_output
  # failed_when: ('100% packet loss' in command_output.stdout)
  ignore_errors: yes
  no_log: true
  changed_when: false

- name: Debug
  debug: 
    msg: "PINGOU"
  when: item.rc == 0
  loop: "{{ command_output.results }}"
  loop_control: 
    label: "Pingando {{ item.item }}"
